# Generated by Django 5.2 on 2025-06-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dj_users", "0001_Initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
