# Generated by Django 5.2 on 2025-07-09 04:47

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dj_catalogs", "0001_initial"),
        ("dj_users", "0002_AddEmailConfirmation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientprofile",
            name="allergies",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="conditions",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="height",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="weight",
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="specialty",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="dj_catalogs.specialty",
            ),
        ),
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lock_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Access"),
                            ("read", "Read Only"),
                            ("none", "No Access"),
                        ],
                        default="full",
                        max_length=10,
                    ),
                ),
                ("object_locked", models.BooleanField(default=False)),
                (
                    "universal_state",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("frozen", "Frozen"),
                            ("active", "Active"),
                            ("effective", "Effective"),
                            ("terminated", "Terminated"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "created_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    django_currentuser.db.models.fields.CurrentUserField(
                        default=django_currentuser.middleware.get_current_authenticated_user,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        on_update=True,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinica",
                "verbose_name_plural": "Clinicas",
            },
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="clinic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="doctors",
                to="dj_users.clinic",
            ),
        ),
    ]
