# Generated by Django 5.2 on 2025-07-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dj_users", "0003_add_clinic_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="imagen",
        ),
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
