# Generated by Django 5.2 on 2025-07-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dj_users", "0004_change_image_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles/%Y/%m/%d/"
            ),
        ),
    ]
