# Generated by Django 5.2 on 2025-07-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dj_users", "0005_change_image_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorprofile",
            name="license_number",
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="professional_license_specialty",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
